# Generated by Django 5.1.7 on 2025-03-19 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_status',
            fields=[
                ('rental_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventarnik',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('inventory_number', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('photo', models.ImageField(upload_to='inventory/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_status')),
            ],
        ),
        migrations.CreateModel(
            name='Arenda',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.CharField(max_length=100)),
                ('arenda_description', models.TextField()),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventarnik')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rentals', to='inventory.personal')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='inventory.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('personal_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Teh_obslujiwanie',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='inventory.personal')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventarnik')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='inventory.personal')),
            ],
        ),
    ]
