# Generated by Django 5.1.7 on 2025-03-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teh_obslujiwanie',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='arenda',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rentals', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='arenda',
            name='renter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='teh_obslujiwanie',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='personal.personal'),
        ),
        migrations.RemoveField(
            model_name='arenda',
            name='rental_id',
        ),
        migrations.RemoveField(
            model_name='inventarnik',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='inventory_status',
            name='rental_status_id',
        ),
        migrations.RemoveField(
            model_name='teh_obslujiwanie',
            name='maintenance_id',
        ),
        migrations.AddField(
            model_name='arenda',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventarnik',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory_status',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teh_obslujiwanie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventarnik',
            name='inventory_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
